version: 2
jobs:
  lint:
    docker:
      - image: node:14.5.0-alpine3.12
    steps:
      - run:
          name: add git
          command: apk add git
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: lint
          command: yarn lint
